AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS SNS Component


Globals:
  Api:
    TracingEnabled: true
    Cors: # see CORS section
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

  Function:
    Timeout: 5
    Runtime: python3.9
    Tracing: Active

Resources:

  MessageQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SNSComponentMessageQueue


  # UpdateQueue:
  #   Type: AWS::SQS::Queue
  #   Properties:
  #     QueueName: SNSComponentUpdateQueue

  # 72.83.171.80

  MessageSender:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SNSComponentMessageSender
      CodeUri: .
      Handler: functions/message-sender/src/app.lambda_handler
      Events:
        NewMessage:
          Type: SQS
          Properties:
            BatchSize: 10
            Enabled: True
            Queue: !GetAtt MessageQueue.Arn

  SNSManager:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SNSComponentSNSManager
      CodeUri: .
      Handler: functions/sns-manager/src/app.lambda_handler
      Events: 
        ApiEvent:
          Type: Api
          Properties:
            Auth:
              ResourcePolicyStatement:
                IpRangeBlacklist:
                  - "*"
                IpRangeWhitelist:
                  - "72.83.171.80"
            Method: ANY
            Path: /{path+}

      # Events: this should reference the queue


