AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS SNS Component

Globals:
  Api:
    TracingEnabled: true
    Cors: # see CORS section
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

  Function:
    Timeout: 15
    Runtime: python3.9
    Tracing: Active

Parameters:
  Env:
    Description: Environment.
    Default: local
    Type: String
    AllowedValues:
      - local
      - dev

Conditions: 
  CreateSharedLayer: !Equals 
    - !Ref Env
    - local

Resources:
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Condition: CreateSharedLayer
    Properties:
      ContentUri: shared/
      CompatibleRuntimes:
        - python3.9

  MessageQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SNSComponentMessageQueue


  UpdateQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SNSComponentUpdateQueue

  # 72.83.171.80

  MessageSender:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SNSComponentMessageSender
      CodeUri: .
      Handler: functions/message_sender/src/app.lambda_handler
      Events:
        NewMessage:
          Type: SQS
          Properties:
            BatchSize: 10
            Enabled: True
            Queue: !GetAtt MessageQueue.Arn


  SNSManager:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SNSComponentSNSManager
      CodeUri: .
      Handler: functions/sns_manager/src/app.lambda_handler
      # Layers:
      #   - 'Fn::If': [!Ref SharedLayer
      Environment:
        Variables:
          LOG_LEVEL: INFO
          POWERTOOLS_SERVICE_NAME: sns_manager
          SNS_ENDPOINT_URL: https://sns.us-east-1.amazonaws.com
      Events: 
        ApiEvent:
          Type: Api
          Properties:
            Auth:
              ApiKeyRequired: True
              Authorizer: None
            Method: ANY
            Path: /{path+}
      Policies:
        - AmazonSNSFullAccess
        - Version: "2012-10-17"
          Statement: 
            - Effect: "Allow"
              Action:
                - sqs:SendMessage
                - sqs:GetQueueAttributes
              Resource: 
                - !GetAtt MessageQueue.Arn
                - !GetAtt UpdateQueue.Arn

  UpdateLogger:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SNSComponentUpdateLogger
      CodeUri: .
      Handler: functions/update_logger/src/app.lambda-handler
      Events:
        NewMessage:
          Type: SQS
          Properties:
            BatchSize: 10
            Enabled: True
            Queue: !GetAtt UpdateQueue.Arn
      Policies:
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Action:
              - dynamodb:PutItem
              - dynamodb:BatchWriteItem
              - dynamodb:GetItem
            Resource: 
              - !GetAtt ChangeLog.Arn

  #need
  #dynamo
  #sns

  ChangeLog:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SNSUpdateTable
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 25
        WriteCapacityUnits: 25
      TimeToLiveSpecification:
        Enabled: True
        AttributeName: "ttl"
      KeySchema: 
        - AttributeName: resource_arn
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: resource_arn
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S

  






