AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS SNS Component

Globals:
  Api:
    TracingEnabled: true
    Cors: # see CORS section
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

  Function:
    Timeout: 15
    Runtime: python3.9
    Tracing: Active

Parameters:
  Env:
    Description: Environment.
    Default: local
    Type: String
    AllowedValues:
      - local
      - dev

Conditions: 
  CreateSharedLayer: !Equals 
    - !Ref Env
    - local

Resources:
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Condition: CreateSharedLayer
    Properties:
      ContentUri: shared/
      CompatibleRuntimes:
        - python3.9

  MessageQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SNSComponentMessageQueue

  # 72.83.171.80

  MessageSender:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SNSComponentMessageSender
      CodeUri: .
      Handler: functions/message_sender/src/app.lambda_handler
      Environment:
        Variables:
          LOG_LEVEL: INFO
          POWERTOOLS_SERVICE_NAME: sns_message_sender
          SQS_ENDPOINT_URL: https://sqs.us-east-1.amazonaws.com
          SNS_ENDPOINT_URL: https://sns.us-east-1.amazonaws.com
      Events:
        NewMessage:
          Type: SQS
          Properties:
            BatchSize: 10
            Enabled: True
            Queue: !GetAtt MessageQueue.Arn


  SNSManager:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SNSComponentSNSManager
      CodeUri: .
      Handler: functions/sns_manager/src/app.lambda_handler
      Layers:
        - !Ref SharedLayer
      Environment:
        Variables:
          LOG_LEVEL: INFO
          POWERTOOLS_SERVICE_NAME: sns_manager
          SNS_ENDPOINT_URL: https://sns.us-east-1.amazonaws.com
          SQS_ENDPOINT_URL: https://sqs.us-east-1.amazonaws.com
          SQS_MESSAGE_ENDPOINT_URL: https://sqs.us-east-1.amazonaws.com/057856323501/SNSComponentMessageQueue

      Events: 
        ApiEvent:
          Type: Api
          Properties:
            Method: ANY
            Path: /{path+}
      Policies:
        - AmazonSNSFullAccess
        - Version: "2012-10-17"
          Statement: 
            - Effect: "Allow"
              Action:
                - sqs:SendMessage
                - sqs:GetQueueAttributes
              Resource: 
                - !GetAtt MessageQueue.Arn
                - !GetAtt UpdateQueue.Arn


  






